# Generated by Django 4.2.16 on 2024-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_remove_movie_trailer_url_movie_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
