# Generated by Django 4.2.16 on 2024-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_popularity_movie_vote_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
